project:
  type: website
  output-dir: docs
website:
  title: "QTM 350"
  page-navigation: true
  back-to-top-navigation: true
  reader-mode: true
  repo-url: https://github.com/emoryPW/qtm350-quiz02
  repo-actions: [issue, source]
  repo-branch: gh-pages
  navbar:
    title: "Gapminder Analysis"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Life Expectancy and GDP"
        href: life-gdp.qmd
      - text: "Life Expectancy and Population"
        href: life-population.qmd
      - text: "Country Analysis"
        href: country.qmd

format: 
  html:
    theme: lux
